#
# Create an instance to act as a MIDI "hub". Assumes the presence of the
# default VPC in the chosen region.
#
# Further information: https://github.com/Brettles/midihub
#

AWSTemplateFormatVersion: 2010-09-09
Description: Deploy MidiHub on Ubuntu

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.medium
    AllowedValues:
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    - t3.xlarge
    - m5.large
    - c5.large
    ConstraintDescription: Must be a valid EC2 instance type.
  ListenerPorts:
    Description: Comma-separated list of UDP ports to listen on
    Type: String
    Default: 5008,5010

Outputs:
  ElasticIP:
    Description: Public IP address of MIDI hub server
    Value: !Ref ElasticIP
  CloudFrontDistribution:
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}/midihub.html'
  ListenerPorts:
    Description: UDP ports for MIDI daemon
    Value: !Ref ListenerPorts
  LambdaFunctionUrl:
    Description: Substitute into midihub.html to see latency updates
    Value: !GetAtt LambdaFunctionUrl.FunctionUrl

Mappings:
  AWSRegion2AMI:
    us-east-1:
      HVM64: ami-0149b2da6ceec4bb0
    us-west-2:
      HVM64: ami-0c09c7eb16d3e8e70
    us-west-1:
      HVM64: ami-03f6d497fceb40069
    eu-west-1:
      HVM64: ami-0fd8802f94ed1c969
    eu-west-2:
      HVM64: ami-04842bc62789b682e
    eu-west-3:
      HVM64: ami-064736ff8301af3ee
    eu-central-1:
      HVM64: ami-06148e0e81e5187c8
    ap-northeast-1:
      HVM64: ami-09b18720cb71042df
    ap-northeast-2:
      HVM64: ami-07d16c043aa8e5153
    ap-northeast-3:
      HVM64: ami-09d2f3a31110c6ad4
    ap-southeast-1:
      HVM64: ami-00e912d13fbb4f225
    ap-southeast-2:
      HVM64: ami-055166f8a8041fbf1
    ap-south-1:
      HVM64: ami-024c319d5d14b463e
    us-east-2:
      HVM64: ami-0d5bf08bc8017c83b
    ca-central-1:
      HVM64: ami-043a72cf696697251
    sa-east-1:
      HVM64: ami-00742e66d44c13cd9

Resources:
  MidiHubInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            "/home/ubuntu/.aws/config":
              content: !Sub |
                [default]
                region = ${AWS::Region}
              mode: '000644'
              owner: ubuntu
              group: ubuntu
            "/home/ubuntu/midiports":
              content: !Sub |
                ${ListenerPorts}
              mode: '000644'
              owner: ubuntu
              group: ubuntu
            "/home/ubuntu/dynamodbtable":
              content: !Sub |
                ${DynamoDBTable}
              mode: '000644'
              owner: ubuntu
              group: ubuntu
            "/home/ubuntu/cloudfrontdistribution":
              content: !Sub |
                ${CloudFrontDistribution}
              mode: '000644'
              owner: ubuntu
              group: ubuntu
            "/home/ubuntu/lambdafunctionurl":
              content: !Sub |
                ${LambdaFunctionUrl.FunctionUrl}
              mode: '000644'
              owner: ubuntu
              group: ubuntu
            "/home/ubuntu/crontab.root":
            "/home/ubuntu/crontab.root":
              content: !Sub |
                @reboot sudo apt-get install linux-modules-extra-`uname -r` -y
              mode: '000644'
              owner: root
              group: root
            "/home/ubuntu/crontab.ubuntu":
              content: !Sub |
                @reboot mv /home/ubuntu/output.log /home/ubuntu/output.old
                @reboot rm /home/ubuntu/output-*.log
                * * * * * (cd /home/ubuntu; ./midihub.py) >>/home/ubuntu/output.log 2>&1
                * * * * * (cd /home/ubuntu; grep Latency *.log | ./update-latency.py)
              mode: '000644'
              owner: ubuntu
              group: ubuntu
    Properties:
      ImageId: !FindInMap [AWSRegion2AMI, !Ref AWS::Region, HVM64]
      InstanceType: !Ref InstanceType
      Tags:
      - Key: Name
        Value: midiHub
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
      - !Ref SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install python3-pip -y
          mkdir -p /opt/aws/
          sudo pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
          sudo ln -s /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
          /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource MidiHubInstance --region ${AWS::Region}
          /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MidiHubInstance --region ${AWS::Region}
          sudo apt-get install cmake g++ pkg-config libavahi-client-dev libfmt-dev alsa-utils alsa-base libghc-alsa-core-dev avahi-utils linux-modules-extra-`uname -r` -y
          sudo pip3 install boto3
          cd /home/ubuntu
          git clone https://github.com/davidmoreno/rtpmidid
          cd rtpmidid
          make build
          cd /home/ubuntu
          git clone https://github.com/Brettles/midihub
          ln midihub/midihub.py midihub.py
          ln midihub/update-latency.py update-latency.py
          cd midihub
          python3 create-s3-bucket.py
          cd /home/ubuntu
          chmod +x midihub.py update-latency.py
          chown -R ubuntu:ubuntu *
          crontab -u ubuntu crontab.ubuntu
          sudo crontab -u root crontab.root
          sudo reboot

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'midiHub-${AWS::StackName}'
      GroupDescription: Enable SSH and RTP for MIDI
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: udp
        FromPort: 5000
        ToPort: 5600
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0

  ElasticIP:
    Type: AWS::EC2::EIP
    DependsOn: MidiHubInstance
    Properties: 
      InstanceId: !Ref MidiHubInstance

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'midiHub-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: Lightsail
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - Lightsail:GetRegions
            Resource: '*'
      - PolicyName: DynamoDB
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: dynamodb:BatchWriteItem
            Resource: !GetAtt DynamoDBTable.Arn
      - PolicyName: CloudFront
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            -  cloudfront:GetDistributionConfig
            -  cloudfront:UpdateDistribution
            Resource: !Sub 'arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'
      - PolicyName: CloudFrontOAC
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: cloudfront:CreateOriginAccessControl
            Resource: '*'
      - PolicyName: S3
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            -  s3:CreateBucket
            -  s3:PutBucketPolicy
            -  s3:PutObject
            Resource: '*'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub 'midiHub-${AWS::StackName}'
      Path: /
      Roles: 
       - !Ref InstanceRole

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'midiHub-${AWS::StackName}'
      AttributeDefinitions:
        - AttributeName: "clientId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "clientId"
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        Enabled: True
        AttributeName: expiryTime

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'midiHub-Lambda-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  DynamoDBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'midiHub-Lambda-DynamoDB-${AWS::StackName}'
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: !GetAtt DynamoDBTable.Arn
            Action: dynamodb:Scan
      Roles:
        - !Ref LambdaRole

  LambdaGetLatencyStats:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'midiHub-GetLatencyStats-${AWS::StackName}'
      Handler: index.lambda_handler
      Runtime: python3.10
      Architectures: [arm64]
      Timeout: 10
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          TableName: !Ref DynamoDBTable
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          import logging
          
          dynamodb = boto3.client('dynamodb')
          
          tableName = os.environ.get('TableName')
          
          logging.basicConfig()
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def lambda_handler(event, context):
              global logger, tableName
          
              if not tableName:
                  logger.error('TableName not set - stopping')
                  return {'statusCode':500, body:'TableName not set'}
          
              paginator = dynamodb.get_paginator('scan')
              iterator = paginator.paginate(TableName=tableName)
          
              output = []
              for page in iterator:
                  for stat in page['Items']:
                      (name,port) = stat['clientId']['S'].split('-')
          
                      item = {'clientName':name, 'clientPort':port, 'timestamp': stat['timestamp']['N'],
                              'averageLatency':stat['averageLatency']['S'], 'maxLatency':stat['maxLatency']['S'],
                              'minLatency':stat['minLatency']['S'], 'lastLatency':stat['lastLatency']['S']}
                      output.append(item)
          
              return(output)

  LambdaFunctionUrl:
    Type: AWS::Lambda::Url
    DependsOn: LambdaGetLatencyStats
    Properties: 
      AuthType: NONE
      Cors: 
        AllowOrigins:
        - '*'
      TargetFunctionArn: !GetAtt LambdaGetLatencyStats.Arn

  LamdbaFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaGetLatencyStats
      FunctionUrlAuthType: NONE
      Action: lambda:InvokeFunctionUrl
      Principal: '*'

  #
  # Dummy CloudFront distribution which will be modified when the EC2 instance
  # starts. A script on the instance will create a S3 bucket; modify the base
  # HTML file with the Lambda function URL; then update the CloudFront
  # distribution to point to the bucket.
  #
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Comment: !Sub 'mibiHub-${AWS::StackName}'
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        PriceClass: 'PriceClass_All'
        Origins:
        - Id: DefaultOrigin
          DomainName: aws.amazon.com
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          TargetOriginId: DefaultOrigin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
